# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitledRew.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 590)
        MainWindow.setStyleSheet("background-color: rgb(66, 66, 66);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plateFind = QtWidgets.QPushButton(self.centralwidget)
        self.plateFind.setGeometry(QtCore.QRect(510, 50, 131, 31))
        self.plateFind.setStyleSheet("background-color: rgb(191, 191, 191);\n"
"")
        self.plateFind.setObjectName("plateFind")
        self.platetxt = QtWidgets.QLabel(self.centralwidget)
        self.platetxt.setGeometry(QtCore.QRect(650, 80, 131, 41))
        self.platetxt.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.platetxt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.platetxt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.platetxt.setText("")
        self.platetxt.setObjectName("platetxt")
        self.lblSurname = QtWidgets.QLabel(self.centralwidget)
        self.lblSurname.setGeometry(QtCore.QRect(510, 170, 47, 21))
        self.lblSurname.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblSurname.setObjectName("lblSurname")
        self.lblName = QtWidgets.QLabel(self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(510, 140, 47, 21))
        self.lblName.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblName.setObjectName("lblName")
        self.img = QtWidgets.QLabel(self.centralwidget)
        self.img.setGeometry(QtCore.QRect(20, 10, 481, 301))
        self.img.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.img.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img.setText("")
        self.img.setScaledContents(True)
        self.img.setObjectName("img")
        self.savecam = QtWidgets.QPushButton(self.centralwidget)
        self.savecam.setGeometry(QtCore.QRect(670, 40, 91, 23))
        self.savecam.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.savecam.setObjectName("savecam")
        self.imchoose = QtWidgets.QPushButton(self.centralwidget)
        self.imchoose.setGeometry(QtCore.QRect(510, 10, 131, 31))
        self.imchoose.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.imchoose.setObjectName("imchoose")
        self.carList = QtWidgets.QTableWidget(self.centralwidget)
        self.carList.setGeometry(QtCore.QRect(20, 320, 811, 241))
        self.carList.setMaximumSize(QtCore.QSize(811, 16777215))
        self.carList.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.carList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.carList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.carList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.carList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.carList.setObjectName("carList")
        self.carList.setColumnCount(8)
        self.carList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.carList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.carList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.carList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.carList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.carList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.carList.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.carList.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.carList.setHorizontalHeaderItem(7, item)
        self.readPlate = QtWidgets.QPushButton(self.centralwidget)
        self.readPlate.setGeometry(QtCore.QRect(510, 90, 131, 31))
        self.readPlate.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.readPlate.setObjectName("readPlate")
        self.txtName = QtWidgets.QLineEdit(self.centralwidget)
        self.txtName.setGeometry(QtCore.QRect(570, 140, 121, 20))
        self.txtName.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.txtName.setObjectName("txtName")
        self.opencam = QtWidgets.QPushButton(self.centralwidget)
        self.opencam.setGeometry(QtCore.QRect(650, 10, 131, 31))
        self.opencam.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.opencam.setObjectName("opencam")
        self.btnSubmit = QtWidgets.QPushButton(self.centralwidget)
        self.btnSubmit.setGeometry(QtCore.QRect(620, 200, 71, 23))
        self.btnSubmit.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.btnSubmit.setObjectName("btnSubmit")
        self.txtSurname = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSurname.setGeometry(QtCore.QRect(570, 170, 121, 20))
        self.txtSurname.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.txtSurname.setObjectName("txtSurname")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget, calendarPopup=True)
        self.dateEdit.setGeometry(QtCore.QRect(510, 290, 110, 22))
        self.dateEdit.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        self.dateEdit.setObjectName("dateEdit")
        self.slctdDate = QtWidgets.QPushButton(self.centralwidget)
        self.slctdDate.setGeometry(QtCore.QRect(630, 290, 61, 23))
        self.slctdDate.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.slctdDate.setObjectName("slctdDate")
        self.showAll = QtWidgets.QPushButton(self.centralwidget)
        self.showAll.setGeometry(QtCore.QRect(750, 290, 81, 23))
        self.showAll.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.showAll.setObjectName("showAll")
        self.img.raise_()
        self.plateFind.raise_()
        self.platetxt.raise_()
        self.lblSurname.raise_()
        self.lblName.raise_()
        self.savecam.raise_()
        self.imchoose.raise_()
        self.carList.raise_()
        self.readPlate.raise_()
        self.txtName.raise_()
        self.opencam.raise_()
        self.btnSubmit.raise_()
        self.txtSurname.raise_()
        self.dateEdit.raise_()
        self.slctdDate.raise_()
        self.showAll.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plateFind.setText(_translate("MainWindow", "Plakayı Bul"))
        self.lblSurname.setText(_translate("MainWindow", "Soyad"))
        self.lblName.setText(_translate("MainWindow", "Ad"))
        self.savecam.setText(_translate("MainWindow", "Kareyi Seç"))
        self.imchoose.setText(_translate("MainWindow", "Resim Seç"))
        item = self.carList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ad"))
        item = self.carList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Soyad"))
        item = self.carList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Plaka"))
        item = self.carList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Giriş Zamanı"))
        item = self.carList.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Çıkış Zamanı"))
        item = self.carList.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Tarih"))
        item = self.carList.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Düzenle"))
        item = self.carList.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Sil"))
        self.readPlate.setText(_translate("MainWindow", "Plakayı Oku"))
        self.opencam.setText(_translate("MainWindow", "Kamerayı Aç"))
        self.btnSubmit.setText(_translate("MainWindow", "Kaydet"))
        self.slctdDate.setText(_translate("MainWindow", "Seç"))
        self.showAll.setText(_translate("MainWindow", "Hepsini Göster"))

